In [1]:
import numpy as np
import cv2

# Function to estimate 3D structure from two views given essential matrix
def estimate_3d_structure(E, points1, points2, K):
    # Decompose essential matrix into rotation and translation
    _, R, t, _ = cv2.recoverPose(E, points1, points2, K)

    # Triangulate points
    P1 = np.hstack((np.eye(3), np.zeros((3, 1)))) # First camera matrix
    P2 = np.hstack((R, t)) # Second camera matrix with R, t
    P1 = K @ P1
    P2 = K @ P2
    points_4d_hom = cv2.triangulatePoints(P1, P2, points1.T, points2.T)
    points_3d = points_4d_hom[:3] / points_4d_hom[3]

    return points_3d.T

# Simulated example
K = np.eye(3) # Intrinsic camera matrix
E = np.eye(3) # Essential matrix for simulated data
points1 = np.random.rand(10, 2) # Points in the first image
points2 = np.random.rand(10, 2) # Corresponding points in the second image
# Estimate 3D structure
structure_3d = estimate_3d_structure(E, points1, points2, K)
print("Estimated 3D structure:\n", structure_3d)

Estimated 3D structure:
 [[ 0.18401615 -0.00126126  0.8195226 ]
 [ 0.11377557  0.04082501  0.89175884]
 [ 0.47271425 -0.01386475  0.65331539]
 [ 0.47471004  0.18097251  0.6339845 ]
 [ 0.06193591  0.76656447  1.24070346]
 [ 0.46635865 -0.10205408  0.58283114]
 [ 0.20799788  0.22239959  1.16049659]
 [ 0.0213952   0.22375939  1.16171725]
 [-0.02351379 -0.18632035 -0.06659168]
 [ 0.23211426 -0.08019522  0.37759384]]
